version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    networks:
      - monitoring
    ports:
      - 9091:9090

  grafana:
    image: grafana/grafana-oss  # use grafana/grafana-enterprise for Grafana Enterprise
    networks:
      - monitoring
    ports:
      - 3002:3000
    environment:
      GF_DATASOURCE: prometheus

  loki:
    image: grafana/loki:latest
    networks:
      - monitoring
    ports:
      - 3100:3100  # Loki UI port

networks:
  monitoring:
    external: false
